### ISSUE TITLE
i need a lil help

### ISSUE THREAD

**Issue by kayden765** [XxB1a/ddos-discord-bot#1]
so when i run code it works fine the bot is up but when i do .ddos it says i need to cop a spot how i use

**Comment by XxB1a** [comment]
Hi Kayden! I see that you didn't read the code thru! You will need to add YOUR Discord User ID to the *owners* list before executing the bot's file! The code needs to have owners, admins, and regular buyers! Once an owner is added, you can use .add_admin and .add_buyer to add administrators and buyers! Please note: Owners cannot add owners without changing the code, and you need to enable Developer Mode to copy User IDs on Discord!

Also, TYSM for reaching out for support <3 ! If you need any extended support, contact me over at XxBiancaXx#4356! @kayden765 

I hope that this helped you :)
